version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: zadanie5-backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    container_name: zadanie5-frontend
    depends_on:
      - backend
